spring.application.name=ondas

# Configurações da AWS
aws.s3.bucket.entrada=ondas-input-privado
aws.region=sa-east-1
# As credenciais (Access Key e Secret Key) da AWS geralmente são passadas
# como variáveis de ambiente por segurança, e o SDK v2 as lê automaticamente!