spring.application.name=ondas

# Configurações de Banco de Dados (Supabase PostgreSQL)
spring.datasource.url=jdbc:postgresql://db.jyddtbhqvsbogorfrizk.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Acque5t@.153684
# Validar schema automatico na inicializacao (mude para validate em producao)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações da AWS
aws.s3.bucket.entrada=ondas-input-privado
aws.region=sa-east-1
# As credenciais (Access Key e Secret Key) da AWS geralmente são passadas
# como variáveis de ambiente por segurança, e o SDK v2 as lê automaticamente!